refactoring

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 IMAGE_NAME="interactive_stego"
-BASE_PATH="./interactive_stego"
+BASE_PATH="./interactive_stego_docker"
 
 if [ ! -d "$BASE_PATH/docker-wine" ]; then
     echo "Downloading base repository..."
@@ -29,24 +29,11 @@ echo "Building image..."
 DOCKER_BUILDKIT=1 docker build \
     --tag birnbaum01/$IMAGE_NAME \
     $BASE_PATH/docker-wine
-
-echo "Starting container..."
-docker run -it \
-    --rm \
-    --hostname="$(hostname)" \
-    --env="DISPLAY" \
-    --volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro" \
-    --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro" \
-    --volume=$(realpath ./io):/home/wineuser/io \
-    --cap-add SYS_ADMIN \
-    --device /dev/fuse \
-    birnbaum01/$IMAGE_NAME /bin/bash
-
-#stop running container
-if [ "$(docker container ls | grep "$IMAGE_NAME" | wc -l)" = "1" ]; then
-    DOCKER_ID=$(docker container ls | grep "$IMAGE_NAME" | cut -d" " -f1)
-    echo "Stopping container '$DOCKER_ID'..."
-    docker stop $DOCKER_ID
+err_lvl=$?
+if [ "$err_lvl" = "0" ]; then
+    echo "Build was successful!"
+    exit 0
+else
+    echo "Build failed with error code $err_lvl!"
+    exit $err_lvl
 fi
-
-exit 0
